const formikData = [
  {
    value: 0,
    name: 'Anotação',
    type: 'annotation',
    item: [
      {
        name: 'formName',
        text: 'Nome',
        element: 'input',
        formName: '',
      },
      {
        name: 'annotation',
        text: 'Anotação',
        element: 'textArea',
        annotation: '',
        crypto: true,
      },
      {
        name: 'description',
        text: 'Descrição',
        element: 'textArea',
        description: '',
      },
    ],
  },
  {
    value: 1,
    name: 'Conta bancária',
    type: 'bankAccount',
    item: [
      {
        name: 'formName',
        text: 'Nome',
        element: 'input',
        formName: '',
      },
      {
        name: 'bank',
        text: 'Banco',
        element: 'input',
        bank: '',
        crypto: false,
      },
      {
        name: 'agency',
        text: 'Agência',
        element: 'input',
        agency: '',
        crypto: false,
      },
      {
        name: 'account',
        text: 'Conta',
        element: 'input',
        account: '',
        crypto: false,
      },
      {
        name: 'password',
        text: 'Senha',
        element: 'input',
        type: 'password',
        password: '',
        crypto: true,
      },
      {
        name: 'description',
        text: 'Descrição',
        element: 'textArea',
        description: '',
      },
    ],
  },
  {
    value: 2,
    name: 'Cartão de crédito',
    type: 'creditCard',
    item: [
      {
        name: 'formName',
        text: 'Nome',
        element: 'input',
        formName: '',
      },
      {
        name: 'cardNumber',
        text: 'Número do cartão',
        element: 'input',
        cardNumber: '',
        crypto: false,
      },
      {
        name: 'validity',
        text: 'Validade',
        element: 'input',
        validity: '',
        crypto: false,
      },
      {
        name: 'cvv',
        text: 'CVV',
        element: 'input',
        cvv: '',
        crypto: true,
      },
      {
        name: 'nameCard',
        text: 'Nome no Cartão',
        element: 'input',
        nameCard: '',
        crypto: false,
      },
      {
        name: 'cpf',
        text: 'CPF',
        element: 'input',
        cpf: '',
        crypto: true,
      },
      {
        name: 'address',
        text: 'Endereço da fatura',
        element: 'input',
        address: '',
        crypto: false,
      },
      {
        name: 'description',
        text: 'Descrição',
        element: 'textArea',
        description: '',
      },
    ],
  },
  {
    value: 3,
    name: 'Email',
    type: 'email',
    item: [
      {
        name: 'formName',
        text: 'Nome',
        element: 'input',
        formName: '',
      },
      {
        name: 'provider',
        text: 'Provedor',
        element: 'input',
        provider: '',
        crypto: false,
      },
      {
        name: 'email',
        text: 'Email',
        element: 'input',
        email: '',
        crypto: false,
      },
      {
        name: 'password',
        text: 'Senha',
        type: 'password',
        element: 'input',
        password: '',
        crypto: true,
      },
      {
        name: 'description',
        text: 'Descrição',
        element: 'textArea',
        description: '',
      },
    ],
  },
  {
    value: 4,
    name: 'FTP',
    type: 'ftp',
    item: [
      {
        name: 'formName',
        text: 'Nome',
        element: 'input',
        formName: '',
      },
      {
        name: 'address',
        text: 'IP/Endereço',
        element: 'input',
        address: '',
        crypto: false,
      },
      {
        name: 'port',
        text: 'Porta',
        element: 'input',
        port: '',
        crypto: false,
      },
      {
        name: 'user',
        text: 'Usuário',
        element: 'input',
        user: '',
        crypto: false,
      },
      {
        name: 'password',
        text: 'Senha',
        type: 'password',
        element: 'input',
        password: '',
        crypto: true,
      },
      {
        name: 'description',
        text: 'Descrição',
        element: 'textArea',
        description: '',
      },
    ],
  },
  {
    value: 5,
    name: 'Kubeconfig',
    type: 'kubeconfig',
    item: [
      {
        name: 'formName',
        text: 'Nome',
        element: 'input',
        formName: '',
      },
      {
        name: 'cluster',
        text: 'Cluster',
        element: 'input',
        cluster: '',
        crypto: false,
      },
      {
        name: 'kubeconfig',
        text: 'Kubeconfig',
        element: 'textArea',
        kubeconfig: '',
        crypto: true,
      },
      {
        name: 'description',
        text: 'Descrição',
        element: 'textArea',
        description: '',
      },
    ],
  },
  {
    value: 6,
    name: 'Licença de Software',
    type: 'softwareLicense',
    item: [
      {
        name: 'formName',
        text: 'Nome',
        element: 'input',
        formName: '',
      },
      {
        name: 'license',
        text: 'Licença',
        element: 'input',
        license: '',
        crypto: true,
      },
      {
        name: 'description',
        text: 'Descrição',
        element: 'textArea',
        description: '',
      },
    ],
  },
  {
    value: 7,
    name: 'Login',
    type: 'login',
    item: [
      {
        name: 'formName',
        text: 'Nome',
        element: 'input',
      },
      {
        name: 'user',
        text: 'Usuário',
        element: 'input',
        crypto: false,
      },
      {
        name: 'password',
        text: 'Senha',
        type: 'password',
        element: 'input',
        crypto: true,
      },
      {
        name: 'description',
        text: 'Descrição',
        element: 'textArea',
      },
    ],
  },
  {
    value: 8,
    name: 'SSH',
    type: 'ssh',
    item: [
      {
        name: 'formName',
        text: 'Nome',
        element: 'input',
        formName: '',
      },
      {
        name: 'sshKeyPrivate',
        text: 'SSH Key Private',
        element: 'input',
        sshKeyPrivate: '',
        crypto: true,
      },
      {
        name: 'sshKeyPublic',
        text: 'SSH Key Public',
        element: 'input',
        sshKeyPublic: '',
        crypto: false,
      },
      {
        name: 'password',
        text: 'Senha',
        type: 'password',
        element: 'input',
        password: '',
        crypto: true,
      },
      {
        name: 'description',
        text: 'Descrição',
        element: 'textArea',
        description: '',
      },
    ],
  },
  {
    value: 9,
    name: 'Servidor',
    type: 'server',
    item: [
      {
        name: 'formName',
        text: 'Nome',
        element: 'input',
        formName: '',
      },
      {
        name: 'address',
        text: 'IP/Endereço',
        element: 'input',
        address: '',
        crypto: false,
      },
      {
        name: 'port',
        text: 'Porta',
        element: 'input',
        port: '',
        crypto: false,
      },
      {
        name: 'protocol',
        text: 'Protocolo',
        element: 'input',
        protocol: '',
        crypto: false,
      },
      {
        name: 'user',
        text: 'Usuário',
        element: 'input',
        user: '',
        crypto: false,
      },
      {
        name: 'password',
        text: 'Senha',
        type: 'password',
        element: 'input',
        password: '',
        crypto: true,
      },
      {
        name: 'key',
        text: 'Chave',
        element: 'input',
        key: '',
        crypto: true,
      },
      {
        name: 'description',
        text: 'Descrição',
        element: 'textArea',
        description: '',
      },
    ],
  },
  {
    value: 10,
    name: 'Site',
    type: 'site',
    item: [
      {
        name: 'formName',
        text: 'Nome',
        element: 'input',
        formName: '',
      },
      {
        name: 'url',
        text: 'URL',
        element: 'input',
        url: '',
        crypto: false,
      },
      {
        name: 'user',
        text: 'Usuário',
        element: 'input',
        user: '',
        crypto: false,
      },
      {
        name: 'password',
        text: 'Senha',
        type: 'password',
        element: 'input',
        password: '',
        crypto: true,
      },
      {
        name: 'description',
        text: 'Descrição',
        element: 'textArea',
        description: '',
      },
    ],
  },
];

export default formikData;
